### ISSUE TITLE
Composer constraint should have an upper bound

### ISSUE THREAD

**Issue by stof** [zendframework/ZendPdf#33]
Current releases of the library are advocating compatibility with all future versions of ``zendframework/zend-stdlib`` (which may be broken already, as version 3 contained a bunch of BC breaks) and of ``zendframework/zend-memory``.
Bound constraints should be used instead

**Comment by Ocramius** [comment]
This library was discontinued and isn't maintained since years, so I doubt that it will be fixed anytime soon.

**Comment by stof** [comment]
Then, it would be great to mark it as abandoned on Packagist and to update the readme to say it is discontinued.
I just found a library depending on this package, which is how I discovered it. and I had no way to know this package is discontinued.

**Comment by weierophinney** [comment]
@stof Done; I've updated the README file, and marked it as abandoned on packagist.
